name: Publish Metaflow Ray (Manual)
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Set up Python 3.x
      uses: actions/setup-python@152ba7c4dd6521b8e9c93f72d362ce03bf6c4f20 # v1.2.3
      with:
        python-version: '3.x'
    - name: Install Python 3.x dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install setuptools build twine
    - name: Build metaflow-ray package
      run: |
        python3 -m build
    - name: Publish metaflow-ray package
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 #v1.14.2
      with:
        user: __token__
        password: ${{ secrets.TWINE_PASSWORD }}
